[theme]
theme = "space-villain"
[icons]
icons = "awesome6"

[[block]]
block = "weather"
format = "$icon $weather ($location) $temp, $wind m/s $direction"
service = { name = "openweathermap", api_key = "6c93f86e8d6ae15fd8c13b3491a1c3c0", city_id = "3117735", units = "metric" }
interval = 300

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
format = "SSD $icon $used/$total $percentage"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
format = "$icon $signal_strength|$device $ip"

[[block]]
block = "memory"
format = "$icon $mem_used/$mem_total($mem_total_used_percents)"

[[block]]
block = "cpu"
format = "$icon $utilization $frequency"
interval = 5

[[block]]
block = "load"
interval = 5
format = "$icon $1m avg: $1m"

[[block]]
block = "temperature"
format = " $icon $max max "
format_alt = " $icon $min min, $max max, $average avg "
interval = 10
chip = "*-isa-*"

[[block]]
block = "docker"
interval = 5
format = "$icon {$running/$total | 0/0}"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20) $play $next |}"

[[block]]
block = "time"
interval = 30
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R')"

[[block]]
block = "pacman"
interval = 600
error_interval = 300
format = " $icon $pacman + $aur = $both updates available "
format_singular = " $icon $both update available "
format_up_to_date = " $icon"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "yay -Qua"

[[block]]
block = "notify"
